config/routes.rb
Rails.application.routes.draw do
  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'

  resources :docs, param: :slug

  root 'docs#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doc.rb
class Doc < ApplicationRecord
  has_many :items
  belongs_to :impact_list, class_name: 'Doc::List'
  belongs_to :implementation_list, class_name: 'Doc::List'

  before_create :generate_slug

  def to_param
    slug
  end

  def whats_next
    positions_by_item.keys
  end

  def as_chart
    positions_by_item.map do |(item, positions)|
      {
        text: item.content,
        x: positions[1],
        y: positions[0]
      }
    end
  end

  private

  def positions_by_item
    @positions_by_item ||= [impact_list, implementation_list].inject({}) do |acc, list|
      list.positions.each do |position|
        acc[position.item] ||= []
        acc[position.item] << position.position
      end
      acc
    end.
    sort_by {|(_item, positions)| positions.sum}.to_h
  end

  def generate_slug
    self.slug = SecureRandom.urlsafe_base64(24)
  end
end

app/models/doc/adding_item.rb
class Doc::AddingItem < Doc
  include Gerund

  accepts_nested_attributes_for :items
  accepts_nested_attributes_for :impact_list
  accepts_nested_attributes_for :implementation_list

  def add_item=(attrs = {})
    return if attrs[:content].blank?
    add_item_to_top_of_all_lists(items.create(attrs))
  end

  private

  def add_item_to_top_of_all_lists(item)
    max_impact_position = impact_list.positions.last&.position || -1
    impact_list.positions.create(item: item, position: max_impact_position + 1)
    implementation_list.positions.create(item: item, position: 0)
  end
end

app/models/doc/creating.rb
class Doc::Creating < Doc
  include Gerund

  before_validation :build_default_lists, on: :create

  private

  def build_default_lists
    build_impact_list(title: 'Impact', max_in_words: 'High', min_in_words: 'Low')
    build_implementation_list(title: 'Implementation', max_in_words: 'Easy', min_in_words: 'Hard')
  end
end

app/models/doc/item.rb
class Doc::Item < ApplicationRecord
  has_many :positions, -> { order 'list_id' }, dependent: :destroy, class_name: 'Doc::List::Position'
end

app/models/doc/list.rb
class Doc::List < ApplicationRecord
  has_many :positions, -> { order 'position' }
  has_many :items, through: :positions

  accepts_nested_attributes_for :positions
end

app/models/doc/list/position.rb
class Doc::List::Position < ApplicationRecord
  belongs_to :item
  belongs_to :list
end

app/models/doc/sorted_list.rb
class Doc::SortedList < ApplicationRecord
  has_many :positions, -> { order 'position' }
  has_many :items, through: :positions

  accepts_nested_attributes_for :positions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  before_action :set_doc, only: [:show, :edit, :update, :destroy]

  # GET /docs
  # GET /docs.json
  def index
    @docs = Doc.all
  end

  # GET /docs/1
  # GET /docs/1.json
  def show
    @doc = @doc.becomes(Doc::AddingItem)
  end

  # GET /docs/new
  def new
    @doc = Doc.new
    @doc = @doc.becomes(Doc::AddingItem)
  end

  # GET /docs/1/edit
  def edit
  end

  # POST /docs
  # POST /docs.json
  def create
    @doc = Doc.new(doc_params)
    @doc = @doc.becomes(Doc::Creating)

    respond_to do |format|
      if @doc.save
        format.html { redirect_to @doc, notice: 'Doc was successfully created.' }
        format.json { render :show, status: :created, location: @doc }
      else
        format.html { render :new }
        format.json { render json: @doc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /docs/1
  # PATCH/PUT /docs/1.json
  def update
    respond_to do |format|
      @doc = @doc.becomes(Doc::AddingItem)
      if @doc.update(doc_params)
        ActionCable.server.broadcast "docs-#{@doc.slug}",
          html: ApplicationController.render(
            template: 'docs/show',
            assigns: {doc: @doc, notice: 'shared', page_title: @page_title}
        )

        format.html { head status: :ok, location: @doc }
        format.json { render :show, status: :ok, location: @doc }
      else
        format.html { render :edit }
        format.json { render json: @doc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /docs/1
  # DELETE /docs/1.json
  def destroy
    @doc.destroy
    respond_to do |format|
      format.html { redirect_to docs_url, notice: 'Doc was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doc
      @doc = Doc.find_by_slug(params[:slug])
      @page_title = @doc&.title
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doc_params
      params.require(:doc).permit(
        :title,
        add_item: [:content],
        items_attributes: [:content, :id],
        impact_list_attributes: [
          :id,
          {positions_attributes: [:position, :id]}
        ],
        implementation_list_attributes: [
          :id,
          {positions_attributes: [:position, :id]}
        ]
      )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/views/doc/items/_item.html.haml
- unless item.new_record?
  %li.list-group-item
    - if defined?(item_f)
      .content-container.not-editable{class: dom_id(item)}
        = item_f.text_field :content,
          class: 'form-control',
          disabled: 'disabled'
      .pull-right
        %a.btn.btn-edit{href: '#', data: {toggle: "editable", target: ".#{dom_id(item)}"}} edit
    - else
      = item.content

app/views/doc/lists/_list.html.haml
= fields_for doc do |f|
  = f.fields_for list_type, list do |list_f|
    .tab-pane{id: list_type}
      .row
        .item-list.col-sm-12
          %h3= list_f.object.title
          %ul.list-group.sortable
            = list_f.fields_for :positions do |position_f|
              %li.item.list-group-item
                %i.fa.fa-ellipsis-v.fa-lg
                %i.fa.fa-ellipsis-v.fa-lg
                = position_f.object.item.content
                = position_f.hidden_field :position, class: 'item-position'

                .move-item-buttons
                  %a.move-up
                    %i.fa.fa-arrow-circle-up.fa-2x
                  %a.move-down
                    %i.fa.fa-arrow-circle-down.fa-2x

app/views/docs/_chart.html.haml
#chart
  .data.hidden{'data-item-count': doc.items.count}
    = doc.as_chart.to_json

app/views/docs/_form.html.haml
= form_for @doc, html: { class: "form-horizontal", role: "form" } do |f|
  -if @doc.errors.any?
    .alert.alert-danger.alert-dismissable{role: "alert"}
      %button.close{type: "button", data: {dismiss: "alert"} }
        %span{aria: {hidden: "true"} } &times;
        %span.sr-only Close
      %h4= "#{pluralize(@doc.errors.count, "error")} prohibited this doc from being saved:"

      %ul
        - @doc.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    .col-sm-12
      = f.label :title, "Give your What's Up Doc a title"
      = f.text_field :title, class: 'form-control', placeholder: '"Life goals", "Joe\'s Ventures", etc'
  .form-group
    .col-sm-12
      = f.submit class: 'btn btn-primary'

app/views/docs/edit.html.haml
.page-header
  = link_to docs_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @doc, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing doc

= render 'form'

app/views/docs/index.html.haml
.page-header
  = link_to new_doc_path, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus
    New Doc
  %h1 Listing docs

.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th Title
        %th Slug
        %th
        %th
        %th

    %tbody
      - @docs.each do |doc|
        %tr
          %td= doc.title
          %td= doc.slug
          %td= link_to 'Show', doc
          %td= link_to 'Edit', edit_doc_path(doc)
          %td= link_to 'Destroy', doc, data: { confirm: 'Are you sure?' }, method: :delete

app/views/docs/new.html.haml
.container
  .row
    .col-sm-6.col-sm-offset-3
      .page-header
        %h1
          Hello!
          %span.emj &#x1F603;

      %p
        A <strong>What's Up Document</strong> helps you discern the most impactful
        thing you could be doing.

      %p
        %u Step 1:
        %strong Enter things
        you could do.

      %p
        %u Step 2:
        %strong Rank
        your things from highest to lowest impact.

      %p
        %u Step 3:
        %strong Rank
        your things from easiest to hardest to implement.

      %p
        %u Step 4:
        %strong Profit!
        See your things on a four-quadrant graph, and
        %em start working on what's up and to the right!

      %h3 Let's get started

      = render 'form'

app/views/docs/show.html.haml
.container
  .page-header.hidden-xs
    %h1
      = @doc.title
      - if @notice
        - if @notice == 'thumbsup'
          .notice-icon.pull-right.emj &#x1F44D;
        - elsif @notice == 'shared'
          %i.fa.fa-user-plus.fa-2x.notice-icon.pull-right

.container
  .row
    .col-sm-4
      = form_for(@doc, remote: true) do |f|
        #doc-steps
          %ul{style: 'position: absolute; top: 0'}
            %li
              %a{href: '#items', 'data-toggle': 'tab'}
            %li
              %a{href: '#impact_list', 'data-toggle': 'tab'}
            %li
              %a{href: '#implementation_list', 'data-toggle': 'tab'}
            %li
              %a{href: '#whats_up', 'data-toggle': 'tab'}

          .tab-content
            .tab-pane#items

              = f.fields_for(:add_item, @doc.items.new) do |item_f|
                .row
                  .col-xs-12
                    %h3 Add Items
                #new-item.row
                  .col-xs-9

                    .form-group
                      = item_f.text_field :content,
                        class: 'form-control',
                        placeholder: '"Solve World Hunger", "Watch a Movie", ...'
                  .col-xs-2
                    .form-group
                      = item_f.submit 'Add', class: 'btn btn-primary'

              .row.items
                .col-sm-12
                  %ul.list-group
                    = f.fields_for(:items, @doc.items.order('created_at DESC')) do |item_f|
                      = render item_f.object, item_f: item_f

            = render f.object.impact_list,
              doc: @doc,
              list_type: :impact_list

            = render f.object.implementation_list,
              doc: @doc,
              list_type: :implementation_list

            .tab-pane#whats_up
              .row.items
                .col-sm-12
                  %h3 Here's What's Up!
                  %ul.list-group
                    = render f.object.whats_next

            .navbar.navbar-inverse.navbar-fixed-bottom.visible-xs-block
              .container-fluid
                %ul.nav.navbar-nav.wizard
                  %li.previous.col-xs-6
                    %button.btn.btn-transparent{href: '#', data: {toggle: 'collapse'}}
                      %i.fa.fa-lg.fa-chevron-left
                      Back
                  %li.next.col-xs-6{style: 'text-align: right'}
                    %button.btn.btn-transparent{href: '#', data: {toggle: 'collapse'}}
                      Next
                      %i.fa.fa-lg.fa-chevron-right

            .navbar.navbar-clear.hidden-xs
              .container-fluid
                %ul.nav.navbar-nav.wizard.navbar-left
                  %li.previous
                    %button.btn{href: '#', data: {toggle: 'collapse'}}
                      %i.fa.fa-lg.fa-chevron-left
                      Back
                %ul.nav.navbar-nav.wizard.navbar-right
                  %li.next
                    %button.btn{href: '#', data: {toggle: 'collapse'}}
                      Next
                      %i.fa.fa-lg.fa-chevron-right

    .col-sm-8.hidden-xs
      = render partial: 'docs/chart', locals: {doc: @doc}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{charset: "utf-8"}
    %meta{content: "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}
    %meta{content: "", name: "description"}
    %meta{content: "", name: "author"}
    %title= [@page_title, "What's Up (Next) Doc"].compact.join(' | ')

    / HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
      = javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js"

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body{class: [controller_name, action_name]}
    %nav.navbar.navbar-inverse.navbar-fixed-top{role: "navigation"}
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{type: "button", data: {toggle: "collapse", target: "#navbar"}, aria: {expanded: "false", controls: "navbar"} }
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to @page_title || "What's Up (Next) Doc", "/", class: "navbar-brand visible-xs-block"
          = link_to "What's Up (Next) Doc", "/", class: "navbar-brand hidden-xs"

          - if @notice
            .visible-xs-block
              - if @notice == 'thumbsup'
                .notice-icon.pull-right.emj &#x1F44D;
              - elsif @notice == 'shared'
                %i.fa.fa-user-plus.fa-lg.notice-icon.pull-right

        #navbar.collapse.navbar-collapse
          %h3.visible-xs-block What's Up Doc
          %ul.nav.navbar-nav
            %li{class: request.path == root_path ? 'active' : ''}
              %a{href: "/"} Home
            %li
              %a{href: "/about"} About
            %li
              %a{href: "/contact"} Contact
    = yield